### PR TITLE
Add exportable product

### PR DESCRIPTION
**Pull request by Entenwilli**
This PR adds an exportable product of the data flow analysis. A pipeline to automatically deploy the application to the update site still needs to be added

### CODE REVIEW

**Comment by Entenwilli** [comment]
This PR should be ready now. @Nicolas-Boltz, please take a look at the definition of the product.
Would you add the editors as imported plug-ins, or would you add them somewhere else to the definition of the product?

Furthermore, we still need to add a way to automatically build the product with Maven/Tycho

**Comment by Entenwilli** [comment]
Currently, the solution fails to build with the following error:
```
Missing requirement: Event Admin 1.6.200.v20230120-0604 (org.eclipse.equinox.event 1.6.200.v20230120-0604) requires 'osgi.extender; (&(osgi.extender=osgi.component)(version>=1.0)(!(version>=2.0)))' but it could not be found
```

**Comment by Entenwilli** [comment]
The dependency issues should be resolved now. Alas, the product cannot be created at this time: The recommended way to build a product is though Tycho/Maven and, as such, Java 17 is not supported by the internal exporter in Eclipse

**Comment by Nicolas-Boltz** [comment]
I will try to get the maven/tycho build working. As the palladio product can be built, it should be possible.

**Pull request merged**
